modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Spirolateral/Railway/issues"
license="All rights reserved"
[[mods]]
modId="railways"
version="${file.jarVersion}"
displayName="Railways"
displayURL="https://www.curseforge.com/minecraft/mc-mods/railways"
credits="Thanks to someone i guess"
authors="Grimmauld, Spirolateral, Pannoniae, CaveJohnson376, Shura, D'Arcy Olla, YeetusDiabetes, Slimeist"
description='''This mod is WIP and something to do with trains'''

[[dependencies.railways]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[38.0,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.railways]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18, 1.19)"
    ordering="NONE"
    side="BOTH"
