modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Spirolateral/Railway/issues"
license="All rights reserved"
[[mods]]
modId="railways"
version="0.1.0"
displayName="Railways"
displayURL="https://www.curseforge.com/minecraft/mc-mods/railways"
credits="Thanks to someone i guess"
authors="Grimmauld, Spirolateral, Pannoniae, CaveJohnson376, Shura, D'Arcy Olla, YeetusDiabetes"
description='''This mod is WIP and something to do with trains'''

[[dependencies.railways]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.railways]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"
