name: Java CI with Gradle

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
  
      - name: Get latest commit short
        id: get_commit
        run: echo "commit=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
  
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
  
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
  
      - name: Build jar
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
  
      - name: Send built file to discord
        uses: sinshutu/upload-to-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: ./build/libs/*.*

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: railways-nightly-${{ steps.get_hash.outputs.sha_short }}
          path: build/libs/
  