on: push
name: Upload jar to testing channel
jobs:
  build-and-send:
    name: Build Jar and send to Discord
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Get commits
        id: commits
        run: echo "::set-output name=commits::" >> git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
      - name: Send building message to discord
        uses: fateyan/action-discord-notifier@v1.2.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message-title: "Building mod ${{ github.ref }} ${{ steps.commits.outputs.commits }}"
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build jar
        run: ./gradlew jar
        env:
          RAILWAYS_VERSION: preview-${{ github.event.after }}
      - name: Send built file to discord
        uses: sinshutu/upload-to-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: ./build/libs/*.*
